# @format
---
# install java and netools
- name: Install Java and Netools
  hosts: 13.40.210.143
  become: yes
  tasks:
    - name: update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: install java 8
      apt: name=openjdk-8-jre-headless

    - name: install nettools
      apt: name=net-tools

# Download and install the nexus installer
- name: Install Java and Netools
  hosts: 13.40.210.143
  tasks:
    - name: download nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /home/ubuntu/nexus

    - name: extract the tar file
      unarchive:
        src: /home/ubuntu/nexus/nexus-3.47.1-01-unix.tar.gz
        dest: /home/ubuntu/nexus
        remote_src: yes
